// AUTO-GENERATED by generate_math_pool.py — do not hand-edit.
// 80 single-digit (1-9) +/- verification items.
//   20 +T / 20 +F / 20 -T / 20 -F

window.MATH_POOL = [
  {
    "problem": "8 - 2",
    "op": "-",
    "displayed": 7,
    "is_true": false
  },
  {
    "problem": "1 + 3",
    "op": "+",
    "displayed": 4,
    "is_true": true
  },
  {
    "problem": "7 - 4",
    "op": "-",
    "displayed": 3,
    "is_true": true
  },
  {
    "problem": "7 - 1",
    "op": "-",
    "displayed": 6,
    "is_true": true
  },
  {
    "problem": "4 - 2",
    "op": "-",
    "displayed": 1,
    "is_true": false
  },
  {
    "problem": "2 + 4",
    "op": "+",
    "displayed": 5,
    "is_true": false
  },
  {
    "problem": "9 - 8",
    "op": "-",
    "displayed": 1,
    "is_true": true
  },
  {
    "problem": "9 - 5",
    "op": "-",
    "displayed": 4,
    "is_true": true
  },
  {
    "problem": "7 + 5",
    "op": "+",
    "displayed": 16,
    "is_true": false
  },
  {
    "problem": "2 - 1",
    "op": "-",
    "displayed": 5,
    "is_true": false
  },
  {
    "problem": "4 - 1",
    "op": "-",
    "displayed": 3,
    "is_true": true
  },
  {
    "problem": "4 + 9",
    "op": "+",
    "displayed": 10,
    "is_true": false
  },
  {
    "problem": "4 + 4",
    "op": "+",
    "displayed": 11,
    "is_true": false
  },
  {
    "problem": "5 - 4",
    "op": "-",
    "displayed": 3,
    "is_true": false
  },
  {
    "problem": "6 - 5",
    "op": "-",
    "displayed": 1,
    "is_true": true
  },
  {
    "problem": "2 + 8",
    "op": "+",
    "displayed": 10,
    "is_true": true
  },
  {
    "problem": "4 + 2",
    "op": "+",
    "displayed": 2,
    "is_true": false
  },
  {
    "problem": "4 - 3",
    "op": "-",
    "displayed": 1,
    "is_true": true
  },
  {
    "problem": "4 - 1",
    "op": "-",
    "displayed": 7,
    "is_true": false
  },
  {
    "problem": "9 - 2",
    "op": "-",
    "displayed": 11,
    "is_true": false
  },
  {
    "problem": "5 + 5",
    "op": "+",
    "displayed": 10,
    "is_true": true
  },
  {
    "problem": "3 + 3",
    "op": "+",
    "displayed": 9,
    "is_true": false
  },
  {
    "problem": "1 - 1",
    "op": "-",
    "displayed": 1,
    "is_true": false
  },
  {
    "problem": "3 + 4",
    "op": "+",
    "displayed": 7,
    "is_true": true
  },
  {
    "problem": "5 - 5",
    "op": "-",
    "displayed": 0,
    "is_true": true
  },
  {
    "problem": "6 + 1",
    "op": "+",
    "displayed": 7,
    "is_true": true
  },
  {
    "problem": "8 + 1",
    "op": "+",
    "displayed": 9,
    "is_true": true
  },
  {
    "problem": "2 + 8",
    "op": "+",
    "displayed": 6,
    "is_true": false
  },
  {
    "problem": "3 - 1",
    "op": "-",
    "displayed": 2,
    "is_true": true
  },
  {
    "problem": "8 - 3",
    "op": "-",
    "displayed": 5,
    "is_true": true
  },
  {
    "problem": "9 + 9",
    "op": "+",
    "displayed": 18,
    "is_true": true
  },
  {
    "problem": "8 + 9",
    "op": "+",
    "displayed": 18,
    "is_true": false
  },
  {
    "problem": "3 + 7",
    "op": "+",
    "displayed": 10,
    "is_true": true
  },
  {
    "problem": "4 + 3",
    "op": "+",
    "displayed": 7,
    "is_true": true
  },
  {
    "problem": "5 - 1",
    "op": "-",
    "displayed": 4,
    "is_true": true
  },
  {
    "problem": "6 - 3",
    "op": "-",
    "displayed": 0,
    "is_true": false
  },
  {
    "problem": "3 + 3",
    "op": "+",
    "displayed": 8,
    "is_true": false
  },
  {
    "problem": "6 - 4",
    "op": "-",
    "displayed": 3,
    "is_true": false
  },
  {
    "problem": "4 - 3",
    "op": "-",
    "displayed": 5,
    "is_true": false
  },
  {
    "problem": "2 - 2",
    "op": "-",
    "displayed": 4,
    "is_true": false
  },
  {
    "problem": "6 - 6",
    "op": "-",
    "displayed": 0,
    "is_true": true
  },
  {
    "problem": "6 - 2",
    "op": "-",
    "displayed": 4,
    "is_true": true
  },
  {
    "problem": "4 - 4",
    "op": "-",
    "displayed": 0,
    "is_true": true
  },
  {
    "problem": "5 + 1",
    "op": "+",
    "displayed": 6,
    "is_true": true
  },
  {
    "problem": "8 - 4",
    "op": "-",
    "displayed": 4,
    "is_true": true
  },
  {
    "problem": "2 + 1",
    "op": "+",
    "displayed": 7,
    "is_true": false
  },
  {
    "problem": "7 - 7",
    "op": "-",
    "displayed": 0,
    "is_true": true
  },
  {
    "problem": "7 + 3",
    "op": "+",
    "displayed": 10,
    "is_true": true
  },
  {
    "problem": "9 + 6",
    "op": "+",
    "displayed": 15,
    "is_true": true
  },
  {
    "problem": "7 + 6",
    "op": "+",
    "displayed": 10,
    "is_true": false
  },
  {
    "problem": "1 - 1",
    "op": "-",
    "displayed": 4,
    "is_true": false
  },
  {
    "problem": "2 + 7",
    "op": "+",
    "displayed": 10,
    "is_true": false
  },
  {
    "problem": "2 - 2",
    "op": "-",
    "displayed": 0,
    "is_true": true
  },
  {
    "problem": "7 - 1",
    "op": "-",
    "displayed": 4,
    "is_true": false
  },
  {
    "problem": "7 - 2",
    "op": "-",
    "displayed": 5,
    "is_true": true
  },
  {
    "problem": "9 + 1",
    "op": "+",
    "displayed": 10,
    "is_true": true
  },
  {
    "problem": "8 + 7",
    "op": "+",
    "displayed": 15,
    "is_true": true
  },
  {
    "problem": "2 + 9",
    "op": "+",
    "displayed": 10,
    "is_true": false
  },
  {
    "problem": "7 + 5",
    "op": "+",
    "displayed": 12,
    "is_true": true
  },
  {
    "problem": "7 + 6",
    "op": "+",
    "displayed": 12,
    "is_true": false
  },
  {
    "problem": "8 + 2",
    "op": "+",
    "displayed": 10,
    "is_true": true
  },
  {
    "problem": "8 + 4",
    "op": "+",
    "displayed": 12,
    "is_true": true
  },
  {
    "problem": "6 + 2",
    "op": "+",
    "displayed": 10,
    "is_true": false
  },
  {
    "problem": "8 + 8",
    "op": "+",
    "displayed": 16,
    "is_true": true
  },
  {
    "problem": "9 - 3",
    "op": "-",
    "displayed": 3,
    "is_true": false
  },
  {
    "problem": "2 + 1",
    "op": "+",
    "displayed": 3,
    "is_true": true
  },
  {
    "problem": "1 - 1",
    "op": "-",
    "displayed": 0,
    "is_true": true
  },
  {
    "problem": "1 + 7",
    "op": "+",
    "displayed": 6,
    "is_true": false
  },
  {
    "problem": "2 - 1",
    "op": "-",
    "displayed": 4,
    "is_true": false
  },
  {
    "problem": "3 + 1",
    "op": "+",
    "displayed": 0,
    "is_true": false
  },
  {
    "problem": "5 - 1",
    "op": "-",
    "displayed": 2,
    "is_true": false
  },
  {
    "problem": "1 + 7",
    "op": "+",
    "displayed": 12,
    "is_true": false
  },
  {
    "problem": "5 - 4",
    "op": "-",
    "displayed": 1,
    "is_true": true
  },
  {
    "problem": "7 - 2",
    "op": "-",
    "displayed": 7,
    "is_true": false
  },
  {
    "problem": "7 + 7",
    "op": "+",
    "displayed": 14,
    "is_true": true
  },
  {
    "problem": "3 + 6",
    "op": "+",
    "displayed": 5,
    "is_true": false
  },
  {
    "problem": "6 - 2",
    "op": "-",
    "displayed": 0,
    "is_true": false
  },
  {
    "problem": "4 - 2",
    "op": "-",
    "displayed": 6,
    "is_true": false
  },
  {
    "problem": "5 + 1",
    "op": "+",
    "displayed": 3,
    "is_true": false
  },
  {
    "problem": "2 - 2",
    "op": "-",
    "displayed": 1,
    "is_true": false
  }
];
